advanced:
  gradient_accumulation:
    enabled: false
    steps: 4
  initialization:
    weight_init: kaiming
  mixed_precision:
    enabled: true
    precision: 16
data:
  augment: true
  augmentation_params:
    flip_probability: 0.5
    intensity_scale: 0.1
    intensity_shift: 0.1
    noise_std: 0.01
    rotation_range: 15.0
    scale_range:
    - 0.9
    - 1.1
  batch_size: 2
  crop_size:
  - 128
  - 128
  - 128
  dataset_name: acdc
  norm_method: zscore
  normalize: true
  num_workers: 8
  persistent_workers: true
  pin_memory: true
  root: ./datasets/acdc
  spacing:
  - 1.5
  - 1.5
  - 1.5
  train_val_split: 0.8
  use_es_ed_only: true
evaluation:
  confusion_matrix: true
  metrics:
  - dice
  - hausdorff95
  - surface_dice
  test_after_training: true
hardware:
  accelerator: gpu
  accumulate_grad_batches: 1
  benchmark: true
  deterministic: false
  gpus: auto
  gradient_clip_val: 1.0
  precision: 16
  strategy: auto
logging:
  experiment_name: acdc_4layer_unet
  filename: acdc-{epoch:02d}-{val_dice_mean:.3f}
  log_every_n_steps: 50
  logger: tensorboard
  mode: max
  monitor: val_dice_mean
  project_name: acdc_gcnn_segmentation
  save_dir: ./checkpoints
  save_last: true
  save_top_k: 3
  tags:
  - acdc
  - cardiac
  - segmentation
  - gcnn
  - 3d
model:
  antialiasing:
    anti_aliasing_kwargs:
      generator: r-s
      sample_type: sample
    apply_antialiasing: true
  dropout_rate: 0.1
  group_config:
    dwn_group_types:
    - - octahedral
      - octahedral
    - - octahedral
      - cycle
    init_group_order: 24
    spatial_subsampling_factors:
    - 1
    - 2
    subsampling_factors:
    - 1
    - 6
  kernel_sizes:
  - 3
  - 3
  model_type: gcnn3d_seg
  num_channels:
  - 1
  - 16
  - 32
  num_classes: 4
  num_layers: 2
test_mode:
  enabled: true
  fast_dev_run: false
  limit_test_batches: 1.0
  limit_train_batches: 0.4
  limit_val_batches: 1.0
  max_epochs: 5
training:
  early_stopping:
    enabled: true
    min_delta: 0.001
    mode: max
    monitor: val_dice_mean
    patience: 20
  loss:
    name: focal_dice
    params:
      alpha: 0.5
      gamma: 2.0
      smooth: 1.0e-06
  max_epochs: 200
  optimizer:
    name: adamw
    params:
      betas:
      - 0.9
      - 0.999
      eps: 1e-8
      lr: 1e-3
      weight_decay: 1e-4
  scheduler:
    name: cosine
    params:
      T_max: 200
      eta_min: 1.0e-06
